services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 0bs
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    shm_size: '1g'

volumes:
  pg_data:

# DATABASE_URL=postgresql://postgres:password@localhost:5432/0bs